<?php

namespace Database\Seeders;

use App\Models\Competencia;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CompetenciaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $competencias = array(
            array("llave" => "CC001", "nombre" => "Aplicar técnicas de conducción en pendiente ascendente y descendente", "definicion" => "Conducir el equipo/vehículo utilizando correctamente la configuración de marcha, frenos y velocidad de acuerdo al porcentaje de inclinación que tiene una pendiente.", "tipo_competencia_id" => 1, "proyecto" => "VP (TRANSVERSAL)", "alcance" => "Equipos Moviles"),
            array("llave" => "CC002", "nombre" => "Verificar que el equipo/vehículo cumpla con la capacidad de carga de acuerdo a recomendaciones del fabricante, normativa y legislación vigente.", "definicion" => "Respetar la máxima capacidad de llenado (líquido) o de carga del equipo/vehículo, considerando las recomendaciones del fabricante y procedimientos de operación, reglamentos de tránsito y normativa vigente.", "tipo_competencia_id" => 1, "proyecto" => "VP (TRANSVERSAL)", "alcance" => "Equipos Moviles"),
            array("llave" => "CC003", "nombre" => "Aplicar procedimientos de coordinación con personal que participa de la tarea y/o en trabajos simultáneos.", "definicion" => "Acción de comunicación y organización del personal que participa en la ejecución de una tarea y/o en trabajos simultáneos en un área en común.", "tipo_competencia_id" => 1, "proyecto" => "VP (TRANSVERSAL)", "alcance" => "Equipos Moviles"),
            array("llave" => "CC004", "nombre" => "Conducir aplicando los límites de velocidad establecidos de acuerdo a la normativa vigente y las condiciones del entorno.", "definicion" => "Respetar límites de velocidad establecidos de acuerdo a señalética, normativa, características del vehículo/equipo y condiciones del entorno.", "tipo_competencia_id" => 1, "proyecto" => "VP (TRANSVERSAL)", "alcance" => "Equipos Moviles"),
            array("llave" => "CC005", "nombre" => "Aplicar requisitos de estándar de fatiga y somnolencia al realizar la tarea", "definicion" => "Respetar y aplicar estándar de fatiga y somnolencia correspondientes para realizar la tarea (horas de sueño, descanso, consumo de medicamentos, entre otros).", "tipo_competencia_id" => 1, "proyecto" => "VP (TRANSVERSAL)", "alcance" => "Equipos Moviles Rigger"),
            array("llave" => "CC006", "nombre" => "Aplicar Plan de Maniobras de Izaje de acuerdo a pauta y/ o procedimiento de trabajo.", "definicion" => "Ejecutar plan de Izaje de acuerdo al documento elaborado para cumplir dicha tarea. Considerando: forma de la carga, peso, elementos de izaje a utilizar, interpretación de tabla de carga, configuración del estrobado, % de capacidad de carga del equipo, evaluación del entorno y superficie en donde se depositará la carga.", "tipo_competencia_id" => 1, "proyecto" => "VP (TRANSVERSAL)", "alcance" => "Equipos Moviles Rigger"),
            array("llave" => "CC007", "nombre" => "Ejecutar maniobras de estacionamiento de acuerdo a procedimiento de trabajo.", "definicion" => "Estacionar el vehículo/equipo en un lugar pertinente y/o habilitado, quedando la cabina desocupada, con el motor apagado e implementando las medidas de seguridad correspondientes, tales como: retirar llaves de contacto, uso de cuñas, direccionar ruedas en pendiente y aplicar freno de estacionamiento.", "tipo_competencia_id" => 1, "proyecto" => "VP (TRANSVERSAL)", "alcance" => "Equipos Moviles"),
            array("llave" => "CC008", "nombre" => "Aplicar técnicas de conducción defensiva de acuerdo a los elementos del entorno durante la operación del equipo", "definicion" => "Aplicar técnicas de conducción a la defensiva, es decir, observar todo lo que sucede en el entorno, con el objetivo de anticiparse a las situaciones de peligro y evitar cualquier tipo de riesgo. El operador/conductor debe saber anticiparse, evitar distracciones y acomodar comportamiento de manejo a los factores de iluminación y visibilidad (encandilamiento). Excluye condiciones climáticas y de terreno adversos.  *La conducción a la defensiva incluye operación del equipo.", "tipo_competencia_id" => 1, "proyecto" => "VP (TRANSVERSAL)", "alcance" => "Equipos Moviles"),
            array("llave" => "CC009", "nombre" => "Respetar la distancia de seguridad respecto de la trayectoria o proyección de una fuente de energía en un área de trabajo. (Exposición a línea de fuego).", "definicion" => "Hace referencia a la distancia de seguridad que debe mantener una persona o equipo de la trayectoria o proyección de una fuente de energía evitando un posible impacto, golpe o atrapamiento por objetos, materiales o cualquier tipo de energía que se libere de manera repentina.  Excluye Interacción hombre máquina (CC 025) y Mantener distancia entre vehículos durante la conducción (CC 044),", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC010", "nombre" => "Ejecutar labores de carga y descarga de material de acuerdo a procedimiento de trabajo y normativa vigente.", "definicion" => "Ejecutar carga y descarga de material a granel de acuerdo a procedimiento de trabajo, el cual considera actividades de posicionamiento del equipo, verificación del estado del terreno y pendiente, como también, el conocimiento y uso de inclinómetro o similar.  Durante la descarga se debe verificar línea de descarga, levantamiento secuencial, y descenso de la tolva una vez terminada la tarea.", "tipo_competencia_id" => 1, "proyecto" => "VP (TRANSVERSAL)", "alcance" => "Equipos Moviles"),
            array("llave" => "CC011", "nombre" => "Ejecutar acceso y descenso seguro del equipo/vehículo de acuerdo a procedimiento de trabajo.", "definicion" => "Acceder y descender del equipo/vehículo de acuerdo a procedimiento, el cual considera que se debe hacer de frente al equipo utilizando los tres puntos de apoyo, con zapatos y manos limpias, no debe saltar ni llevar objetos que se puedan enganchar y escalera y pasamanos deben estar limpios. Verificar superficie del suelo antes de bajar (pendiente, piso irregular, humedad, barro, hielo nieve, baches, piedras)", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC012", "nombre" => "Realizar tareas cercanas a líneas eléctricas energizadas de acuerdo a procedimiento de trabajo.", "definicion" => "Cumplir con el procedimiento de trabajo para actividades de traslado u operación que se ejecutan en un área que está cercana a líneas eléctricas energizadas. Al respecto, se debe considerar la distancia mínima de acercamiento y solicitar las autorizaciones específicas cuando corresponda.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC013", "nombre" => "Realizar trabajo en altura de acuerdo a procedimiento de trabajo.", "definicion" => "Cumplir con el procedimiento de trabajo en altura, el cual considera el uso del Sistema de Protección contra Caídas (SPDC) y uso de puntos de anclaje certificado.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC014", "nombre" => "Gestionar solicitudes de permisos, autorizaciones específicas y requisitos documentales de acuerdo a procedimiento de trabajo.", "definicion" => "Acción de elaborar y solicitar permisos y/o autorizaciones específicas para ejecutar la tarea y/o ingresar al área de trabajo incluyendo. Estos documentos consideran: planos, requisitos documentales, entrega e inducción del área (cuando corresponda), acreditación del equipo y operador, entre otros.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC015", "nombre" => "Verificar el cierre de puertas, ventanas, barandas y portalón en el equipo/vehículo de acuerdo a procedimientos de trabajo.", "definicion" => "Acción de asegurar el cierre de puertas, escotillas, ventanas, barandas y portalón del vehículo/equipo. Acción de cerrar y/o asegurar el cierre de puertas, escotillas, ventanas, barandas y portalón del vehículo/equipo.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC016", "nombre" => "Ejecutar carguío de combustible en el equipo/vehículo de acuerdo a procedimientos de trabajo.", "definicion" => "Ejecutar el carguío de combustible en el vehículo/equipo de acuerdo a procedimiento de trabajo.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC017", "nombre" => "Aplicar el Reglamento de Operación de Invierno de acuerdo a procedimiento.", "definicion" => "Aplicar el Reglamento de Operación de Invierno, tomando en consideración las alertas invernales, zonas de avalancha, postura de cadenas, porte y uso del equipamiento y EPP. (RECCO)", "tipo_competencia_id" => 2, "proyecto" => "PROYECTO DAND", "alcance" => "Equipos Moviles"),
            array("llave" => "CC018", "nombre" => "Utilizar los frenos durante las actividades de conducción, operación, detención y estacionamiento del equipo/vehículo de acuerdo con procedimientos de trabajo y recomendaciones del fabricante.", "definicion" => "Uso del sistema de frenos durante toda actividad relacionada a la conducción, operación, detención y/o estacionamiento de un equipo/vehículo de acuerdo al procedimiento establecido.", "tipo_competencia_id" => 2, "proyecto" => "PROYECTO RAJO INCA PROYECTO DAND", "alcance" => "Equipos Moviles"),
            array("llave" => "CC019", "nombre" => "Cumplir con los parámetros operacionales del equipo de acuerdo a procedimiento de trabajo e instrucciones del fabricante.", "definicion" => "Utilizar el vehículo/equipo dentro de los límites de operación definidos en manual de fabricante, tales como la inclinación máxima y compactación requerida del terreno, cercanía a bordes o zanjas, velocidad del viento, etc.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC020", "nombre" => "Utilizar elementos de izaje de acuerdo al tipo de carga y procedimiento de trabajo.", "definicion" => "Refiere a la correcta elección, inspección y uso de los elementos de izaje de acuerdo al tipo de carga (peso, volumen y forma), capacidad de carga, limitaciones de uso y recomendaciones del fabricante. Asimismo, se deben proteger los cantos vivos y asegurar certificación de puntos de anclaje.", "tipo_competencia_id" => 2, "proyecto" => "PROYECTO DAND", "alcance" => "Equipos Moviles Rigger"),
            array("llave" => "CC021", "nombre" => "Aplicar técnicas de conducción defensiva en condiciones climáticas adversas de acuerdo a procedimiento de trabajo e instrucciones del área.", "definicion" => "Aplicar técnicas de conducción a la defensiva* adecuando el comportamiento de manejo según las condiciones climáticas adversas (vientos fuertes, nevazón, lluvia, etc.)  *La conducción a la defensiva incluye operación del equipo.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC022", "nombre" => "Aplicar técnicas de conducción defensiva en condiciones de terreno adversas de acuerdo a procedimiento de trabajo.", "definicion" => "Aplicar técnicas de conducción a la defensiva*, adecuando el comportamiento de manejo según las condiciones del terreno que puedan dificultar la conducción y generar una liberación de energía del equipo/vehículo.  Considerando las condiciones del terreno: estabilidad del suelo, presencia de baches, existencia de elementos sobresalientes, pendiente, perdida de adherencia por carpeta de rodado mojada, húmeda o con hielo, presencia de barro, nieve, etc.)  *La conducción a la defensiva incluye operación del equipo.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC023", "nombre" => "Identificar las fallas en el equipo durante la conducción/operación del equipo/vehículo, y actuar según lo establecido por el fabricante y/o procedimiento de trabajo.", "definicion" => "Comprende la acción de:  - Identificar todas las señales del panel del vehículo o equipo (testigos luminosos).  - Detectar una falla en el vehículo/equipo durante la conducción u operación. Las fallas pueden ser detectadas a través de: indicadores de advertencia en el panel del equipo, dispositivos de alarma, ruidos, vibraciones, humo, problemas en la dirección, frenos y neumáticos, entre otros.  - Interpretar los diferentes niveles o categorias de advertencia existentes en el equipo y actuar según su criticidad y lo establecido por el fabricante o procedimiento de trabajo.  *Proyecto Rajo Inca focaliza los problemas de direccion y de los indicadores del panel del equipo.", "tipo_competencia_id" => 2, "proyecto" => "PROYECTO RAJO INCA PROYECTO DAND", "alcance" => "Equipos Moviles"),
            array("llave" => "CC024", "nombre" => "Ejecutar labores de izaje de acuerdo a normativa internacional de señales manuales.", "definicion" => "Conocer y aplicar las señales manuales para labores de izaje.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC025", "nombre" => "Mantener distancia mínima de acercamiento de un vehículo y/o equipo en movimiento hacia un peatón de acuerdo a procedimiento de trabajo. (interacción hombre/máquina).", "definicion" => "Establecer y respetar la distancia mínima de acercamiento de un vehículo/equipo en movimiento hacia un peatón, ya sea por traslado u operación.", "tipo_competencia_id" => 2, "proyecto" => "PROYECTO DAND", "alcance" => "Equipos Moviles"),
            array("llave" => "CC026", "nombre" => "Ejecutar maniobras de giro del equipo/vehículo de acuerdo a procedimiento de trabajo y recomendaciones del fabricante.", "definicion" => "Aplicar técnicas de conducción y/o operación a la defensiva durante una maniobra de giro, controlando la velocidad y el uso de marcha. Asimismo, requiere tener en consideración el peralte del camino.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC027", "nombre" => "Ejecutar maniobras de izaje y cargas suspendidas de acuerdo a procedimiento de trabajo y recomendaciones del fabricante.", "definicion" => "Ejecutar una maniobra de izaje y cargas suspendidas, controlando la velocidad, estabilidad y oscilación de la carga.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC028", "nombre" => "Ejecutar maniobras de excavación de acuerdo a procedimiento de trabajo y recomendaciones del fabricante.", "definicion" => "Ejecutar maniobras de excavación de acuerdo a procedimiento de trabajo, considerando planos o referencias topográficas, capacidad del equipo y las recomendaciones del fabricante.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC029", "nombre" => "Ejecutar maniobras de adelantamiento a un vehículo y/o equipo en movimiento de acuerdo a procedimientos de trabajo e instrucciones del área.", "definicion" => "Aplicar técnicas de conducción y/o operación a la defensiva durante una maniobra de adelantamiento de un vehículo y/o equipo en movimiento, controlando la velocidad y el uso de la marcha adecuada.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC030", "nombre" => "Aplicar procedimiento de detención del equipo/vehículo.", "definicion" => "Es la acción propia de detener el equipo/vehículo quedando el conductor/operador dentro de la cabina. La detención comprende: la disminución de la velocidad, situarse en un entorno pertinente/habilitado, poner el freno y activar luz intermitente según corresponda (el motor del equipo puede quedar indistintamente encendido o apagado).", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC031", "nombre" => "Ejecutar maniobras de retroceso de acuerdo a procedimientos de trabajo e instrucciones del área.", "definicion" => "Aplicar técnicas de conducción y/o operación a la defensiva durante una maniobra de retroceso según procedimientos de trabajo e instrucciones del área. Considera verificar elementos del entorno y asegurar correcta visualización de puntos ciegos.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC032", "nombre" => "Realizar puesta en marcha del equipo/vehículo de acuerdo a procedimiento de trabajo y recomendaciones del fabricante.", "definicion" => "Ejecutar la maniobra de puesta en marcha del equipo/vehículo; esta actividad considera reinicio de marcha.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC033", "nombre" => "Actuar conforme a la información de señalética, letreros y/o elementos de segregación.", "definicion" => "Respetar la señalética vial, letreros, loros, semáforos, elementos de segregación, etc. durante la conducción y/o operacion del vehiculo o equipo.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC034", "nombre" => "Ejecutar la segregación del área de acuerdo a instructivos del área, procedimiento de trabajo y normativa vigente.", "definicion" => "Delimitar un área de trabajo con el fin de evitar el ingreso de personal o equipos que no participan en la tarea. Considera el uso de barreras, colocar señalética de advertencia, cerrar accesos y evacuar personal.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC035", "nombre" => "Aplicar tarjeta verde de acuerdo a procedimientos de trabajo y normativa vigente.", "definicion" => "Hacer uso de la tarjeta verde en situaciones que impliquen la exposición de una persona/equipo a un riesgo no controlado durante la ejecución de un trabajo o tarea específica.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC036", "nombre" => "Utilizar distintos sistemas de comunicación de acuerdo a procedimientos de trabajo y normativa vigente.", "definicion" => "Utilizar correctamente los sistemas de comunicación establecidos y validados en el procedimiento de trabajo para un área o tarea específica (radios de comunicación, códigos de bocina, luces).", "tipo_competencia_id" => 2, "proyecto" => "PROYECTO RAJO INCA", "alcance" => "Equipos Moviles Rigger"),
            array("llave" => "CC038", "nombre" => "Aplicar el reglamento de conducción interior mina (rajo, superficie, subterránea y camino industrial).", "definicion" => "Cumplir con los requisitos aplicables definidos en el Reglamento de Conducción General de la Faena, o específico del área de trabajo (Mina Subterránea, Mina rajo, Plantas, etc.). Considera el uso adecuado del equipamiento necesario para transitar en el área donde se realiza la tarea y el conocimiento de las obligaciones, prohibiciones y sanciones establecidas.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC040", "nombre" => "Asegurar la carga durante el proceso de carga o descarga de acuerdo al procedimiento de trabajo y normativa vigente.", "definicion" => "Asegurar la carga o bulto de acuerdo al tipo y forma de esta durante el proceso de carga o descarga, utilizando la sujeción y amarre que corresponda cuando sea necesario. Además, considera asegurar la estabilidad y soporte de la carga una vez ubicada en el sector definido.", "tipo_competencia_id" => 2, "proyecto" => "PROYECTO RAJO INCA", "alcance" => "Equipos Moviles"),
            array("llave" => "CC041", "nombre" => "Aplicar reglamento de perforación y tronadura considerando los radios de Tronadura.", "definicion" => "Cumplir con los requisitos aplicables definidos en el reglamento de perforación y tronadura. Considera respetar los radios de tronadura y segregación establecidas.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC042", "nombre" => "Aplicar procedimiento de trabajo durante la secuencia de carguío de material.", "definicion" => "Ejecutar la secuencia de carguío de material de acuerdo a procedimiento de trabajo y seguridad, el cual considera el posicionamiento del equipo en el área de carguío, la verificación del estado del terreno y pendiente, tipo de materal, granulometría y presencia de bolones.  En el caso de realizar traspaso de material a otro equipo, se debe realizar la coordinación entre operadores y verificar la estiba, entre otros.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC043", "nombre" => "Realizar inspección preoperacional del equipo de acuerdo a procedimiento de trabajo.", "definicion" => "Realizar inspección preoperacional del vehículo/equipo, evaluando cada uno de los componentes o sistemas definidos en la lista de chequeo, dejando el registro respectivo.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC044", "nombre" => "Cumplir con la distancia mínima de seguridad entre vehículos y/o equipos durante la conducción y/o operación de acuerdo a procedimientos de trabajo y normativa vigente.", "definicion" => "Respetar la distancia mínima con relación a otros vehículos/equipos, durante la conducción y/o operacion.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC045", "nombre" => "Utilizar elementos de seguridad durante la conducción y operación del equipo de acuerdo a procedimiento de trabajo.", "definicion" => "Uso de cinturón de seguridad y equipo de protección personal (EPP) tanto para el conductor/operador como para los pasajeros.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC046", "nombre" => "Estibar y/o Verificar la correcta estiba de la carga del equipo de acuerdo a procedimiento de trabajo.", "definicion" => "Estibar y/o Verificar la correcta estiba de una carga (fija o a granel) manteniendo una distribución adecuada en el equipo, considerando el centro de gravedad del conjunto carga-equipo, de manera de mantener su estabilidad durante la ejecución de la tarea.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC048", "nombre" => "Realizar el acople y desacople de la barra de perforación de acuerdo a procedimiento de trabajo.", "definicion" => "Realizar el acople y desacople de la barra de perforación en el equipo según procedimiento de trabajo.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC049", "nombre" => "Realizar inicio de marcha en vehículo de transporte de pasajeros de acuerdo a procedimiento de trabajo.", "definicion" => "Verificar al momento de iniciar la marcha del vehículo que los pasajeros se encuentren debidamente sentados en sus respectivos asientos.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC050", "nombre" => "Realizar el tránsito del vehículo/equipo de acuerdo a la ruta establecida en faena minera.", "definicion" => "Tomar conocimiento de la ruta a transitar previo al ingreso al área. Asimismo, el conductor deberá respetar la ruta establecida de acuerdo a procedimiento de trabajo e indicaciones de seguridad.", "tipo_competencia_id" => 3, "proyecto" => "null", "alcance" => "Equipos Moviles"),
            array("llave" => "CC051", "nombre" => "Utilizar la caja de transmisión del vehículo o equipo, de acuerdo a recomendaciones del fabricante y condiciones del entorno.", "definicion" => "Uso correcto de la caja de transmisión durante la conducción/operación del vehículo/equipo, considerando las recomendaciones del fabricante y del terreno (excluye conducción en pendiente).", "tipo_competencia_id" => 2, "proyecto" => "PROYECTO RAJO INCA", "alcance" => "Equipos Moviles"),
            array("llave" => "CC052", "nombre" => "Aplicar procedimiento de cambios de neumáticos en vehículos livianos y/o transporte de pasajeros de acuerdo a estándar y recomendaciones del fabricante.", "definicion" => "Refiere al cumplimiento del procedimiento de cambio de neumáticos de vehículos livianos y transporte de pasajeros. Incluye: Aplicar controles específicos de la tarea, verificación documental de la ejecución del torqueo de pernos o tuercas de neumáticos según periodicidad definida en plan de mantenimiento y cada vez que se realice el cambio de neumáticos.", "tipo_competencia_id" => 2, "proyecto" => "PROYECTO DAND", "alcance" => "Equipos Moviles"),
            array("llave" => "CC053", "nombre" => "Aplicar control de energías (energía cero) y bloqueo al intervenir equipos y sistemas eléctricos de acuerdo a procedimiento y normativa vigente.", "definicion" => "Comprende: verificar planos o diagramas del equipo o sistema eléctrico involucrado, identificando los puntos de corte de energía que corresponda a la actividad.  Realizar corte visible o efectivo de todas las fuentes de tensión.  Realizar bloqueo en la posición de apertura y señalizar con tarjeta y candado de bloqueo.  Verificación ausencia de tensión (energía cero), en cada uno de los conductores, antes y después de la operación.  Verificación de fuentes de energía alternativos o no formalizadas., cuando corresponda. Poner a tierra y /o en cortocircuito (para MT AT).  Delimitar zona de trabajo. Realizar permiso de trabajo.  Considera bloqueo mecánico en aquellas tareas que corresponda.", "tipo_competencia_id" => 1, "proyecto" => "VP (TRANSVERSAL)", "alcance" => "Mantenedor Eléctrico"),
            array("llave" => "CC054", "nombre" => "Utilizar elementos de Protección personal y ropa de trabajo requeridos para la intervención de equipos y sistemas eléctricos de acuerdo a procedimiento y normativa vigente.", "definicion" => "Utilizar elementos de Protección personal y ropa de trabajo requeridos de acuerdo al tipo de actividad y los niveles de tensión involucrado en la intervención de equipos y sistemas eléctricos de acuerdo a lo establecido en procedimiento de trabajo, recomendación de fabricante y normativa vigente .  Así mismo debe verificar el buen estado de los EPP y ropa de trabajo. Considera EPP básicos y específicos para el desarrollo de la tarea.", "tipo_competencia_id" => 1, "proyecto" => "VP (TRANSVERSAL)", "alcance" => "Mantenedor Eléctrico"),
            array("llave" => "CC055", "nombre" => "Realizar el ART de la tarea de acuerdo a procedimientos de trabajo y normativa vigente.", "definicion" => "Realizar el ART asegurando la identificación de peligros y evaluación de riesgos de la tarea y aplicar los controles operacionales establecidos para controlar el riesgo de acuerdo a procedimientos de trabajo y normativa vigente. (Cumplimiento de Controles Críticos definidos)  Comprende adicionalmente hacer uso de la tarjeta verde en situaciones que impliquen la exposición de una persona a un riesgo no controlado durante la ejecución de un trabajo o tarea específica.", "tipo_competencia_id" => 1, "proyecto" => "VP (TRANSVERSAL)", "alcance" => "Mantenedor Eléctrico"),
            array("llave" => "CC056", "nombre" => "Realizar energización de equipos eléctricos de acuerdo a procedimiento de trabajo y normativa vigente.", "definicion" => "Comprende: Coordinación de la actividad con el dueño del área y encargado del equipo o sistema eléctrico.  Conocimiento del equipo o sistema eléctrico a operar.  Realizar inspección visual previa de cada uno de los componentes involucrados en el equipo o sistema eléctrico (buen estado, existencia de cables sueltos, contaminación superficial, polvo, humedad, etc).  Realizar maniobra de acuerdo a recomendaciones del fabricante Ubicación fuera de la línea de la apertura del gabinete.", "tipo_competencia_id" => 3, "proyecto" => "VP (TRANSVERSAL)", "alcance" => "Mantenedor Eléctrico"),
            array("llave" => "CC057", "nombre" => "Utilizar Herramientas, instrumentos y dispositivos requeridos para realizar intervenciones en equipos y sistemas eléctricos de acuerdo a procedimiento y normativa vigente.", "definicion" => "Verificación del buen estado de la herramienta instrumentos o dispositivos; asegurando que sean adecuados para el tipo y nivel de riesgo eléctrico (nivel de tensión) y comprobar la certificación o calibración cuando corresponda.  Asegurar el uso correcto de las herramientas instrumentos o dispositivos de acuerdo a recomendaciones de fabricante, procedimiento de trabajo y normativa vigente.  Comprende herramientas manuales, eléctricas neumáticas, hidráulicas, pértigas, detector de ausencia de tensión, etc.", "tipo_competencia_id" => 3, "proyecto" => "VP (TRANSVERSAL)", "alcance" => "Mantenedor Eléctrico"),
            array("llave" => "CC058", "nombre" => "Aplicar procedimientos de planificación y coordinación con personal que participa de la tarea y/o en trabajos simultáneos.", "definicion" => "Acción de Planificación inicial, comunicación y organización del personal que participa en la ejecución de una tarea y/o en trabajos simultáneos en un área en común.", "tipo_competencia_id" => 3, "proyecto" => "VP (TRANSVERSAL)", "alcance" => "Mantenedor Eléctrico"),
            array("llave" => "CC059", "nombre" => "Aplicar sistema de extinción y/o supresión de incendio frente a la presencia de humo o fuego en el equipo", "definicion" => "Aplicar sistema de extinción y/o supresión de incendio frente a la presencia de humo o fuego en el equipo  Considera:  1. Conocer sistemas de extinción de incendio que tiene el equipo (automatico, manual (portátil) y semiautomatico).  2. Uso y manejo del sistema de extinción de incendio.  3. Conocer agentes extintores de incendio (polvo químico seco, espuma, agua pulverizada, CO2).  4. Verificar que el SEI se encuentra con su fecha de mantención vigente.", "tipo_competencia_id" => 1, "proyecto" => "VP (TRANSVERSAL)", "alcance" => "Equipos Moviles"),
            array("llave" => "CC060", "nombre" => "Aplicar procedimiento de emergencias frente a situaciones de emergencia.", "definicion" => "Aplicar plan de emergencia que se ha definido para situaciones relacionadas con: Humo, incendio (equipo o área de trabajo), pérdida de control del equipo, sismo, condiciones climáticas adversas, caidas de roca, reventón de neumático, derrumbe, entre otras.", "tipo_competencia_id" => 3, "proyecto" => "VP (TRANSVERSAL)", "alcance" => "Equipos Moviles Mantenedor Eléctrico"),
            /*array("llave" => "IMP001", "nombre" => "Las tareas asignadas son realizadas, cumpliendo con los procedimientos de seguridad existentes, aclarando dudas y solicitando información o documentos en caso de no contar con esta información, de acuerdo con procedimiento de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP002", "nombre" => "El control de su salud y estado físico es efectuado, manteniendo una condición apropiada para la ejecución de las tareas encomendadas y comunicando a supervisor en caso de no estar en condiciones adecuadas para realizar la tarea en forma segura, de acuerdo a procedimiento de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP003", "nombre" => "El análisis de requerimientos de seguridad del área es realizado con pares y superiores, detectando condiciones que puedan representar riesgos potenciales o manifiestos para las personas que trabajen o transiten por las proximidades del área en que se realizarán los trabajos, de acuerdo a procedimiento de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP004", "nombre" => "La notificación a pares y supervisores, en caso de detectar condiciones que pudiesen representar riesgos potenciales o manifiestos para las personas que trabajen o transiten por las proximidades del área en que se realizarán los trabajos, es realizada de acuerdo a procedimiento de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP005", "nombre" => "Las charlas de seguridad son abordadas de manera propositiva, exponiendo su visión respecto a la gestión de la seguridad y presentando ideas constructivas, de acuerdo a procedimiento de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP006", "nombre" => "La pauta de trabajo es revisada, clarificando potenciales dudas, de acuerdo a procedimiento del área de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP007", "nombre" => "El análisis de riesgo asociado a las labores que cumplirá en el turno es realizado y registrado en formato correspondiente, de acuerdo a procedimiento de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP008", "nombre" => "Los estándares de seguridad asociados al equipamiento (EPP) y a la ejecución de los trabajos (bloqueos, confinamientos, condiciones sub-estándar) son verificados, de acuerdo a procedimiento de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP009", "nombre" => "Las condiciones de riesgo emergentes que pudieran afectar a las personas y/o los equipos son comunicadas inmediatamente a supervisor o quien corresponda, de acuerdo a procedimiento de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP010", "nombre" => "El análisis de riesgos del trabajo (ART) a efectuar es ejecutado de acuerdo a pauta de análisis de riesgo (ART), procedimientos de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP011", "nombre" => "El estado general del vehículo es inspeccionado de acuerdo a lista de verificación, procedimientos de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP012", "nombre" => "Las condiciones de los sistemas del vehículo son verificadas de acuerdo a lista de verificación procedimientos de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP013", "nombre" => "Los accesorios, dispositivos de seguridad y documentos del vehículo son verificados de acuerdo a procedimiento de trabajo y normativa legal vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP014", "nombre" => "La carga del combustible es realizada de acuerdo a centro de distribución establecido, procedimientos de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP015", "nombre" => "Los riesgos potenciales y peligros presentes en camino industrial de faena minera son identificados de acuerdo a técnicas de conducción aplicadas en faenas mineras, estándares de seguridad, condiciones climatológicas, procedimientos de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP016", "nombre" => "Los riesgos potenciales y peligros presentes en camino industrial de faena minera son controlados de acuerdo a técnicas de conducción aplicadas en faenas mineras, estándares de seguridad, condiciones climatológicas, procedimientos de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP017", "nombre" => "El vehículo de transporte es conducido de acuerdo a protocolo de conducción eficiente, señaléticas de tránsito, tipo de camino, procedimientos de trabajo, itinerario programado y normativa legal vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP018", "nombre" => "Las maniobras de conducción son realizadas de acuerdo a técnicas de conducción aplicadas en faenas mineras, condiciones climatológicas, tipo de camino procedimientos de trabajo y normativa legal vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP019", "nombre" => "La distancia con los vehículos es mantenida de acuerdo a técnicas de conducción aplicadas en faenas mineras, control de riesgos, tipo de camino, procedimiento de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP020", "nombre" => "Las condiciones generales del vehículo son monitoreadas durante el trayecto de acuerdo a procedimientos de trabajo y normativa legal vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP021", "nombre" => "Las maniobras de estacionamiento son realizadas de acuerdo a zona establecida, procedimientos de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP022", "nombre" => "El personal es trasladado de acuerdo a itinerario, zona establecida, procedimientos de trabajo y normativa legal vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP023", "nombre" => "El estado final de las labores es reportado a jefatura de acuerdo a procedimientos de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP024", "nombre" => "La información requerida para el cumplimiento de la tarea es verificada de acuerdo con las instrucciones de personal de caminos, garitas de control, letreros, procedimientos de trabajo y normativas vigentes.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP025", "nombre" => "Las zonas de descanso, puntos de abastecimiento de combustible, salidas de emergencia son identificadas de acuerdo con tipo de camino industrial, procedimientos de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP026", "nombre" => "Las condiciones en caminos industriales son identificadas de acuerdo con técnicas de conducción aplicadas en área industrial, control de riesgos, zonas peligrosas, tipos de caminos, climas, procedimientos de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP027", "nombre" => "Las contingencias en el transporte (deslizamientos de nieve, barro, piedras o bloques de hielo) son detectados de acuerdo con técnicas de conducción aplicadas en área industrial severa, control de riesgos, zonas peligrosas, procedimiento de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP028", "nombre" => "Las contingencias o emergencias durante la conducción por el área industrial severa son comunicadas al personal de caminos y jefatura de acuerdo con ubicación, condiciones de la situación, procedimiento de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP029", "nombre" => "Las soluciones a las contingencias son identificadas de acuerdo con estándares de seguridad, procedimientos de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP030", "nombre" => "Las acciones de control de contingencias son realizadas de acuerdo con protocolo de emergencia, técnicas de conducción, control de riesgos, zonas peligrosas, procedimientos de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP031", "nombre" => "Los implementos requeridos para contingencias en ruta son utilizados de acuerdo con procedimientos de trabajo y normativa legal vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP032", "nombre" => "Las acciones de control de contingencias son monitoreadas (hacer seguimiento) de acuerdo con procedimientos de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP033", "nombre" => "El estado final de las contingencias y medidas de control es reportado a jefatura directa de acuerdo con procedimientos de trabajo y normativa vigente.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP034", "nombre" => "Aplicar técnicas de conducción y operación de acuerdo al manual del fabricante", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP035", "nombre" => "Opera el equipo según las definiciones del Plan y reglamento de transito de la compañia.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP036", "nombre" => "Participa en las charla de seguridad en forma positiva.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP037", "nombre" => "Mantiene en su poder la tarjeta verde", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP038", "nombre" => "Realiza el análisis de riesgo del trabajo asignado.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP039", "nombre" => "Elementos de protección personal (EPP) apropiado para la tarea.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP040", "nombre" => "Revisa la pauta de trabajo del día. Aclara dudas que se le presentan con su líder o supervisor.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP041", "nombre" => "Verifica que el vehículo cuenta con los accesorios de seguridad y la documentación del vehículo se encuentra en orden.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP043", "nombre" => "Mantiene distancia adecuada con otros vehículos de acuerdo a técnicas de conducción aplicadas en faenas mineras, condiciones climatológicas , procedimientos de trabajo.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP044", "nombre" => "Comunica al personal de camino y jefatura las contingencias o emergencia durante la conducción.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),
            array("llave" => "IMP045", "nombre" => "Reporta el estado final de las contingencias y medidas de control de acuerdo a procedimiento.", "definicion" => "Criterio Impronta Mine", "tipo_competencia_id" => 4),*/
        );
        foreach ($competencias as $competencia) {
            Competencia::create($competencia);
        }
    }
}